on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  attestations: write

name: VS Handy Daub

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          # For 1.22.7 (as of writing this comment)
          dotnet-version: '10.0.x'

      - name: Run Cake Build
        run: dotnet run --project ZZCakeBuild/CakeBuild.csproj

      # GENERATE SIGSTORE PROVENANCE
      - name: Attest Build Artifacts
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: 'Releases/*.zip'

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: Releases/*.zip
